Algoritmo "Capgemini - Tipos"

Var
//literal=string
   p1, p2, p3: caractere
   n1, n2, n3: inteiro

Inicio
  Escreval ("Digite a palavra 1:")
  leia(p1)
  Escreval ("Digite a palavra 2:")
  leia(p2)

  Escreval ("Digite o primeiro numero:")
  leia(n1)
  Escreval ("Digite o segundo numero:")
  leia(n2)

  p3 <- p1 + p2
  n3 <- n1 + n2
  // <- = atribuicao
  Escreval (p3)

Fimalgoritmo
