Algoritmo "Capgemini - Trabalhando com Algoritmos"
//treinamento dado por Marcelo, via processo Start da Capgemini
// meu primeiro contato com o VisualG
// ja tenho conhecimento em algoritmos e variaveis, mas achei interessante aprender o uso desse interpretador

Var
//literal=string
   nome: caractere
   sobrenome: caractere
   nomeCompleto: caractere

Inicio
  Escreval ("Informe o seu nome")
  leia(nome)
  Escreval ("Informe o seu sobrenome")
  leia(sobrenome)
  nomeCompleto <- nome + " " + sobrenome
  Escreval (nomeCompleto)
  leia (nomeCompleto)
Fimalgoritmo

